development:
  adapter: postgresql
  encoding: unicode
  database: eventclub_development
  pool: 5
  username: postgres
  password: 123456
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: eventclub_test
  pool: 5
  username: postgres
  password: 123456
  host: localhost
